#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("TestRecyclerView.Resource", IsApplication=true)]

namespace TestRecyclerView
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010004
			public const int cardBackgroundColor = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int cardCornerRadius = 2130771973;
			
			// aapt resource value: 0x7f010006
			public const int cardElevation = 2130771974;
			
			// aapt resource value: 0x7f010007
			public const int cardMaxElevation = 2130771975;
			
			// aapt resource value: 0x7f010009
			public const int cardPreventCornerOverlap = 2130771977;
			
			// aapt resource value: 0x7f010008
			public const int cardUseCompatPadding = 2130771976;
			
			// aapt resource value: 0x7f01000a
			public const int contentPadding = 2130771978;
			
			// aapt resource value: 0x7f01000e
			public const int contentPaddingBottom = 2130771982;
			
			// aapt resource value: 0x7f01000b
			public const int contentPaddingLeft = 2130771979;
			
			// aapt resource value: 0x7f01000c
			public const int contentPaddingRight = 2130771980;
			
			// aapt resource value: 0x7f01000d
			public const int contentPaddingTop = 2130771981;
			
			// aapt resource value: 0x7f010000
			public const int layoutManager = 2130771968;
			
			// aapt resource value: 0x7f010002
			public const int reverseLayout = 2130771970;
			
			// aapt resource value: 0x7f010001
			public const int spanCount = 2130771969;
			
			// aapt resource value: 0x7f010003
			public const int stackFromEnd = 2130771971;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f070000
			public const int cardview_dark_background = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int cardview_light_background = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int cardview_shadow_end_color = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int cardview_shadow_start_color = 2131165187;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f040003
			public const int cardview_compat_inset_shadow = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int cardview_default_elevation = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int cardview_default_radius = 2130968581;
			
			// aapt resource value: 0x7f040000
			public const int item_touch_helper_max_drag_scroll_per_frame = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int item_touch_helper_swipe_escape_max_velocity = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int item_touch_helper_swipe_escape_velocity = 2130968578;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int scrollBar_new_00000 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int scrollBar_new_00001 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int scrollBar_new_00002 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int scrollBar_new_00003 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int scrollBar_new_00004 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int scrollBar_new_00005 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int scrollBar_new_00006 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int scrollBar_new_00007 = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int scrollBar_new_00008 = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int scrollBar_new_00009 = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int scrollBar_new_00010 = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int scrollBar_new_00011 = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int scrollBar_new_00012 = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int scrollBar_new_00013 = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int scrollBar_new_00014 = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int scrollBar_new_00015 = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int scrollBar_new_00016 = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int scrollBar_new_00017 = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int scrollBar_new_00018 = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int scrollBar_new_00019 = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int scrollBar_new_00020 = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int scrollBar_new_00021 = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int scrollBar_new_00022 = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int scrollBar_new_00023 = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int scrollBar_new_00024 = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int scrollBar_new_00025 = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int scrollBar_new_00026 = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int scrollBar_new_00027 = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int scrollBar_new_00028 = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int scrollBar_new_00029 = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int scrollBar_new_00030 = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int scrollBar_new_00031 = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int scrollBar_new_00032 = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int scrollBar_new_00033 = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int scrollBar_new_00034 = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int scrollBar_new_00035 = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int scrollBar_new_00036 = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int scrollBar_new_00037 = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int scrollBar_new_00038 = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int scrollBar_new_00039 = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int scrollBar_new_00040 = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int scrollBar_new_00041 = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int scrollBar_new_00042 = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int scrollBar_new_00043 = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int scrollBar_new_00044 = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int scrollBar_new_00045 = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int scrollBar_new_00046 = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int scrollBar_new_00047 = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int scrollBar_new_00048 = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int scrollBar_new_00049 = 2130837554;
			
			// aapt resource value: 0x7f020033
			public const int scrollBar_new_00050 = 2130837555;
			
			// aapt resource value: 0x7f020034
			public const int scrollBar_new_00051 = 2130837556;
			
			// aapt resource value: 0x7f020035
			public const int scrollBar_new_00052 = 2130837557;
			
			// aapt resource value: 0x7f020036
			public const int scrollBar_new_00053 = 2130837558;
			
			// aapt resource value: 0x7f020037
			public const int scrollBar_new_00054 = 2130837559;
			
			// aapt resource value: 0x7f020038
			public const int scrollBar_new_00055 = 2130837560;
			
			// aapt resource value: 0x7f020039
			public const int scrollBar_new_00056 = 2130837561;
			
			// aapt resource value: 0x7f02003a
			public const int scrollBar_new_00057 = 2130837562;
			
			// aapt resource value: 0x7f02003b
			public const int scrollBar_new_00058 = 2130837563;
			
			// aapt resource value: 0x7f02003c
			public const int scrollBar_new_00059 = 2130837564;
			
			// aapt resource value: 0x7f02003d
			public const int scrollBar_new_00060 = 2130837565;
			
			// aapt resource value: 0x7f02003e
			public const int scrollBar_new_00061 = 2130837566;
			
			// aapt resource value: 0x7f02003f
			public const int scrollBar_new_00062 = 2130837567;
			
			// aapt resource value: 0x7f020040
			public const int scrollBar_new_00063 = 2130837568;
			
			// aapt resource value: 0x7f020041
			public const int scrollBar_new_00064 = 2130837569;
			
			// aapt resource value: 0x7f020042
			public const int scrollBar_new_00065 = 2130837570;
			
			// aapt resource value: 0x7f020043
			public const int scrollBar_new_00066 = 2130837571;
			
			// aapt resource value: 0x7f020044
			public const int scrollBar_new_00067 = 2130837572;
			
			// aapt resource value: 0x7f020045
			public const int scrollBar_new_00068 = 2130837573;
			
			// aapt resource value: 0x7f020046
			public const int scrollBar_new_00069 = 2130837574;
			
			// aapt resource value: 0x7f020047
			public const int scrollBar_new_00070 = 2130837575;
			
			// aapt resource value: 0x7f020048
			public const int scrollBar_new_00071 = 2130837576;
			
			// aapt resource value: 0x7f020049
			public const int scrollBar_new_00072 = 2130837577;
			
			// aapt resource value: 0x7f02004a
			public const int scrollBar_new_00073 = 2130837578;
			
			// aapt resource value: 0x7f02004b
			public const int scrollBar_new_00074 = 2130837579;
			
			// aapt resource value: 0x7f02004c
			public const int scrollBar_new_00075 = 2130837580;
			
			// aapt resource value: 0x7f02004d
			public const int scrollBar_new_00076 = 2130837581;
			
			// aapt resource value: 0x7f02004e
			public const int scrollBar_new_00077 = 2130837582;
			
			// aapt resource value: 0x7f02004f
			public const int scrollBar_new_00078 = 2130837583;
			
			// aapt resource value: 0x7f020050
			public const int scrollBar_new_00079 = 2130837584;
			
			// aapt resource value: 0x7f020051
			public const int scrollBar_new_00080 = 2130837585;
			
			// aapt resource value: 0x7f020052
			public const int scrollBar_new_00081 = 2130837586;
			
			// aapt resource value: 0x7f020053
			public const int scrollBar_new_00082 = 2130837587;
			
			// aapt resource value: 0x7f020054
			public const int scrollBar_new_00083 = 2130837588;
			
			// aapt resource value: 0x7f020055
			public const int scrollBar_new_00084 = 2130837589;
			
			// aapt resource value: 0x7f020056
			public const int scrollBar_new_00085 = 2130837590;
			
			// aapt resource value: 0x7f020057
			public const int scrollBar_new_00086 = 2130837591;
			
			// aapt resource value: 0x7f020058
			public const int scrollBar_new_00087 = 2130837592;
			
			// aapt resource value: 0x7f020059
			public const int scrollBar_new_00088 = 2130837593;
			
			// aapt resource value: 0x7f02005a
			public const int scrollBar_new_00089 = 2130837594;
			
			// aapt resource value: 0x7f02005b
			public const int scrollBar_new_00090 = 2130837595;
			
			// aapt resource value: 0x7f02005c
			public const int scrollBar_new_00091 = 2130837596;
			
			// aapt resource value: 0x7f02005d
			public const int scrollBar_new_00092 = 2130837597;
			
			// aapt resource value: 0x7f02005e
			public const int scrollBar_new_00093 = 2130837598;
			
			// aapt resource value: 0x7f02005f
			public const int scrollBar_new_00094 = 2130837599;
			
			// aapt resource value: 0x7f020060
			public const int scrollBar_new_00095 = 2130837600;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050001
			public const int imageView = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int item_touch_helper_previous_elevation = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int recyclerView = 2131034114;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int ImageCardView = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f080001
			public const int ApplicationName = 2131230721;
			
			// aapt resource value: 0x7f080000
			public const int Hello = 2131230720;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060001
			public const int Base_CardView = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int CardView = 2131099648;
			
			// aapt resource value: 0x7f060002
			public const int CardView_Dark = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int CardView_Light = 2131099651;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] CardView = new int[] {
					16843071,
					16843072,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982};
			
			// aapt resource value: 1
			public const int CardView_android_minHeight = 1;
			
			// aapt resource value: 0
			public const int CardView_android_minWidth = 0;
			
			// aapt resource value: 2
			public const int CardView_cardBackgroundColor = 2;
			
			// aapt resource value: 3
			public const int CardView_cardCornerRadius = 3;
			
			// aapt resource value: 4
			public const int CardView_cardElevation = 4;
			
			// aapt resource value: 5
			public const int CardView_cardMaxElevation = 5;
			
			// aapt resource value: 7
			public const int CardView_cardPreventCornerOverlap = 7;
			
			// aapt resource value: 6
			public const int CardView_cardUseCompatPadding = 6;
			
			// aapt resource value: 8
			public const int CardView_contentPadding = 8;
			
			// aapt resource value: 12
			public const int CardView_contentPaddingBottom = 12;
			
			// aapt resource value: 9
			public const int CardView_contentPaddingLeft = 9;
			
			// aapt resource value: 10
			public const int CardView_contentPaddingRight = 10;
			
			// aapt resource value: 11
			public const int CardView_contentPaddingTop = 11;
			
			public static int[] RecyclerView = new int[] {
					16842948,
					2130771968,
					2130771969,
					2130771970,
					2130771971};
			
			// aapt resource value: 0
			public const int RecyclerView_android_orientation = 0;
			
			// aapt resource value: 1
			public const int RecyclerView_layoutManager = 1;
			
			// aapt resource value: 3
			public const int RecyclerView_reverseLayout = 3;
			
			// aapt resource value: 2
			public const int RecyclerView_spanCount = 2;
			
			// aapt resource value: 4
			public const int RecyclerView_stackFromEnd = 4;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
