#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("TestRecyclerView.Resource", IsApplication=true)]

namespace TestRecyclerView
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7F010000
			public const int alpha = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int fastScrollEnabled = 2130771969;
			
			// aapt resource value: 0x7F010002
			public const int fastScrollHorizontalThumbDrawable = 2130771970;
			
			// aapt resource value: 0x7F010003
			public const int fastScrollHorizontalTrackDrawable = 2130771971;
			
			// aapt resource value: 0x7F010004
			public const int fastScrollVerticalThumbDrawable = 2130771972;
			
			// aapt resource value: 0x7F010005
			public const int fastScrollVerticalTrackDrawable = 2130771973;
			
			// aapt resource value: 0x7F010006
			public const int font = 2130771974;
			
			// aapt resource value: 0x7F010007
			public const int fontProviderAuthority = 2130771975;
			
			// aapt resource value: 0x7F010008
			public const int fontProviderCerts = 2130771976;
			
			// aapt resource value: 0x7F010009
			public const int fontProviderFetchStrategy = 2130771977;
			
			// aapt resource value: 0x7F01000A
			public const int fontProviderFetchTimeout = 2130771978;
			
			// aapt resource value: 0x7F01000B
			public const int fontProviderPackage = 2130771979;
			
			// aapt resource value: 0x7F01000C
			public const int fontProviderQuery = 2130771980;
			
			// aapt resource value: 0x7F01000D
			public const int fontProviderSystemFontFamily = 2130771981;
			
			// aapt resource value: 0x7F01000E
			public const int fontStyle = 2130771982;
			
			// aapt resource value: 0x7F01000F
			public const int fontVariationSettings = 2130771983;
			
			// aapt resource value: 0x7F010010
			public const int fontWeight = 2130771984;
			
			// aapt resource value: 0x7F010011
			public const int layoutManager = 2130771985;
			
			// aapt resource value: 0x7F010012
			public const int recyclerViewStyle = 2130771986;
			
			// aapt resource value: 0x7F010013
			public const int reverseLayout = 2130771987;
			
			// aapt resource value: 0x7F010014
			public const int spanCount = 2130771988;
			
			// aapt resource value: 0x7F010015
			public const int stackFromEnd = 2130771989;
			
			// aapt resource value: 0x7F010016
			public const int ttcIndex = 2130771990;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7F020000
			public const int androidx_core_ripple_material_light = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int androidx_core_secondary_text_default_material_light = 2130837505;
			
			// aapt resource value: 0x7F020002
			public const int notification_action_color_filter = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int notification_icon_bg_color = 2130837507;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7F030000
			public const int compat_button_inset_horizontal_material = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int compat_button_inset_vertical_material = 2130903041;
			
			// aapt resource value: 0x7F030002
			public const int compat_button_padding_horizontal_material = 2130903042;
			
			// aapt resource value: 0x7F030003
			public const int compat_button_padding_vertical_material = 2130903043;
			
			// aapt resource value: 0x7F030004
			public const int compat_control_corner_material = 2130903044;
			
			// aapt resource value: 0x7F030005
			public const int compat_notification_large_icon_max_height = 2130903045;
			
			// aapt resource value: 0x7F030006
			public const int compat_notification_large_icon_max_width = 2130903046;
			
			// aapt resource value: 0x7F030007
			public const int fastscroll_default_thickness = 2130903047;
			
			// aapt resource value: 0x7F030008
			public const int fastscroll_margin = 2130903048;
			
			// aapt resource value: 0x7F030009
			public const int fastscroll_minimum_range = 2130903049;
			
			// aapt resource value: 0x7F03000A
			public const int item_touch_helper_max_drag_scroll_per_frame = 2130903050;
			
			// aapt resource value: 0x7F03000B
			public const int item_touch_helper_swipe_escape_max_velocity = 2130903051;
			
			// aapt resource value: 0x7F03000C
			public const int item_touch_helper_swipe_escape_velocity = 2130903052;
			
			// aapt resource value: 0x7F03000D
			public const int notification_action_icon_size = 2130903053;
			
			// aapt resource value: 0x7F03000E
			public const int notification_action_text_size = 2130903054;
			
			// aapt resource value: 0x7F03000F
			public const int notification_big_circle_margin = 2130903055;
			
			// aapt resource value: 0x7F030010
			public const int notification_content_margin_start = 2130903056;
			
			// aapt resource value: 0x7F030011
			public const int notification_large_icon_height = 2130903057;
			
			// aapt resource value: 0x7F030012
			public const int notification_large_icon_width = 2130903058;
			
			// aapt resource value: 0x7F030013
			public const int notification_main_column_padding_top = 2130903059;
			
			// aapt resource value: 0x7F030014
			public const int notification_media_narrow_margin = 2130903060;
			
			// aapt resource value: 0x7F030015
			public const int notification_right_icon_size = 2130903061;
			
			// aapt resource value: 0x7F030016
			public const int notification_right_side_padding_top = 2130903062;
			
			// aapt resource value: 0x7F030017
			public const int notification_small_icon_background_padding = 2130903063;
			
			// aapt resource value: 0x7F030018
			public const int notification_small_icon_size_as_large = 2130903064;
			
			// aapt resource value: 0x7F030019
			public const int notification_subtext_size = 2130903065;
			
			// aapt resource value: 0x7F03001A
			public const int notification_top_pad = 2130903066;
			
			// aapt resource value: 0x7F03001B
			public const int notification_top_pad_large_text = 2130903067;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F040000
			public const int Icon = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int notification_action_background = 2130968577;
			
			// aapt resource value: 0x7F040002
			public const int notification_bg = 2130968578;
			
			// aapt resource value: 0x7F040003
			public const int notification_bg_low = 2130968579;
			
			// aapt resource value: 0x7F040004
			public const int notification_bg_low_normal = 2130968580;
			
			// aapt resource value: 0x7F040005
			public const int notification_bg_low_pressed = 2130968581;
			
			// aapt resource value: 0x7F040006
			public const int notification_bg_normal = 2130968582;
			
			// aapt resource value: 0x7F040007
			public const int notification_bg_normal_pressed = 2130968583;
			
			// aapt resource value: 0x7F040008
			public const int notification_icon_background = 2130968584;
			
			// aapt resource value: 0x7F040009
			public const int notification_template_icon_bg = 2130968585;
			
			// aapt resource value: 0x7F04000A
			public const int notification_template_icon_low_bg = 2130968586;
			
			// aapt resource value: 0x7F04000B
			public const int notification_tile_bg = 2130968587;
			
			// aapt resource value: 0x7F04000C
			public const int notify_panel_notification_icon_bg = 2130968588;
			
			// aapt resource value: 0x7F04000D
			public const int scrollBar_new_00000 = 2130968589;
			
			// aapt resource value: 0x7F04000E
			public const int scrollBar_new_00001 = 2130968590;
			
			// aapt resource value: 0x7F04000F
			public const int scrollBar_new_00002 = 2130968591;
			
			// aapt resource value: 0x7F040010
			public const int scrollBar_new_00003 = 2130968592;
			
			// aapt resource value: 0x7F040011
			public const int scrollBar_new_00004 = 2130968593;
			
			// aapt resource value: 0x7F040012
			public const int scrollBar_new_00005 = 2130968594;
			
			// aapt resource value: 0x7F040013
			public const int scrollBar_new_00006 = 2130968595;
			
			// aapt resource value: 0x7F040014
			public const int scrollBar_new_00007 = 2130968596;
			
			// aapt resource value: 0x7F040015
			public const int scrollBar_new_00008 = 2130968597;
			
			// aapt resource value: 0x7F040016
			public const int scrollBar_new_00009 = 2130968598;
			
			// aapt resource value: 0x7F040017
			public const int scrollBar_new_00010 = 2130968599;
			
			// aapt resource value: 0x7F040018
			public const int scrollBar_new_00011 = 2130968600;
			
			// aapt resource value: 0x7F040019
			public const int scrollBar_new_00012 = 2130968601;
			
			// aapt resource value: 0x7F04001A
			public const int scrollBar_new_00013 = 2130968602;
			
			// aapt resource value: 0x7F04001B
			public const int scrollBar_new_00014 = 2130968603;
			
			// aapt resource value: 0x7F04001C
			public const int scrollBar_new_00015 = 2130968604;
			
			// aapt resource value: 0x7F04001D
			public const int scrollBar_new_00016 = 2130968605;
			
			// aapt resource value: 0x7F04001E
			public const int scrollBar_new_00017 = 2130968606;
			
			// aapt resource value: 0x7F04001F
			public const int scrollBar_new_00018 = 2130968607;
			
			// aapt resource value: 0x7F040020
			public const int scrollBar_new_00019 = 2130968608;
			
			// aapt resource value: 0x7F040021
			public const int scrollBar_new_00020 = 2130968609;
			
			// aapt resource value: 0x7F040022
			public const int scrollBar_new_00021 = 2130968610;
			
			// aapt resource value: 0x7F040023
			public const int scrollBar_new_00022 = 2130968611;
			
			// aapt resource value: 0x7F040024
			public const int scrollBar_new_00023 = 2130968612;
			
			// aapt resource value: 0x7F040025
			public const int scrollBar_new_00024 = 2130968613;
			
			// aapt resource value: 0x7F040026
			public const int scrollBar_new_00025 = 2130968614;
			
			// aapt resource value: 0x7F040027
			public const int scrollBar_new_00026 = 2130968615;
			
			// aapt resource value: 0x7F040028
			public const int scrollBar_new_00027 = 2130968616;
			
			// aapt resource value: 0x7F040029
			public const int scrollBar_new_00028 = 2130968617;
			
			// aapt resource value: 0x7F04002A
			public const int scrollBar_new_00029 = 2130968618;
			
			// aapt resource value: 0x7F04002B
			public const int scrollBar_new_00030 = 2130968619;
			
			// aapt resource value: 0x7F04002C
			public const int scrollBar_new_00031 = 2130968620;
			
			// aapt resource value: 0x7F04002D
			public const int scrollBar_new_00032 = 2130968621;
			
			// aapt resource value: 0x7F04002E
			public const int scrollBar_new_00033 = 2130968622;
			
			// aapt resource value: 0x7F04002F
			public const int scrollBar_new_00034 = 2130968623;
			
			// aapt resource value: 0x7F040030
			public const int scrollBar_new_00035 = 2130968624;
			
			// aapt resource value: 0x7F040031
			public const int scrollBar_new_00036 = 2130968625;
			
			// aapt resource value: 0x7F040032
			public const int scrollBar_new_00037 = 2130968626;
			
			// aapt resource value: 0x7F040033
			public const int scrollBar_new_00038 = 2130968627;
			
			// aapt resource value: 0x7F040034
			public const int scrollBar_new_00039 = 2130968628;
			
			// aapt resource value: 0x7F040035
			public const int scrollBar_new_00040 = 2130968629;
			
			// aapt resource value: 0x7F040036
			public const int scrollBar_new_00041 = 2130968630;
			
			// aapt resource value: 0x7F040037
			public const int scrollBar_new_00042 = 2130968631;
			
			// aapt resource value: 0x7F040038
			public const int scrollBar_new_00043 = 2130968632;
			
			// aapt resource value: 0x7F040039
			public const int scrollBar_new_00044 = 2130968633;
			
			// aapt resource value: 0x7F04003A
			public const int scrollBar_new_00045 = 2130968634;
			
			// aapt resource value: 0x7F04003B
			public const int scrollBar_new_00046 = 2130968635;
			
			// aapt resource value: 0x7F04003C
			public const int scrollBar_new_00047 = 2130968636;
			
			// aapt resource value: 0x7F04003D
			public const int scrollBar_new_00048 = 2130968637;
			
			// aapt resource value: 0x7F04003E
			public const int scrollBar_new_00049 = 2130968638;
			
			// aapt resource value: 0x7F04003F
			public const int scrollBar_new_00050 = 2130968639;
			
			// aapt resource value: 0x7F040040
			public const int scrollBar_new_00051 = 2130968640;
			
			// aapt resource value: 0x7F040041
			public const int scrollBar_new_00052 = 2130968641;
			
			// aapt resource value: 0x7F040042
			public const int scrollBar_new_00053 = 2130968642;
			
			// aapt resource value: 0x7F040043
			public const int scrollBar_new_00054 = 2130968643;
			
			// aapt resource value: 0x7F040044
			public const int scrollBar_new_00055 = 2130968644;
			
			// aapt resource value: 0x7F040045
			public const int scrollBar_new_00056 = 2130968645;
			
			// aapt resource value: 0x7F040046
			public const int scrollBar_new_00057 = 2130968646;
			
			// aapt resource value: 0x7F040047
			public const int scrollBar_new_00058 = 2130968647;
			
			// aapt resource value: 0x7F040048
			public const int scrollBar_new_00059 = 2130968648;
			
			// aapt resource value: 0x7F040049
			public const int scrollBar_new_00060 = 2130968649;
			
			// aapt resource value: 0x7F04004A
			public const int scrollBar_new_00061 = 2130968650;
			
			// aapt resource value: 0x7F04004B
			public const int scrollBar_new_00062 = 2130968651;
			
			// aapt resource value: 0x7F04004C
			public const int scrollBar_new_00063 = 2130968652;
			
			// aapt resource value: 0x7F04004D
			public const int scrollBar_new_00064 = 2130968653;
			
			// aapt resource value: 0x7F04004E
			public const int scrollBar_new_00065 = 2130968654;
			
			// aapt resource value: 0x7F04004F
			public const int scrollBar_new_00066 = 2130968655;
			
			// aapt resource value: 0x7F040050
			public const int scrollBar_new_00067 = 2130968656;
			
			// aapt resource value: 0x7F040051
			public const int scrollBar_new_00068 = 2130968657;
			
			// aapt resource value: 0x7F040052
			public const int scrollBar_new_00069 = 2130968658;
			
			// aapt resource value: 0x7F040053
			public const int scrollBar_new_00070 = 2130968659;
			
			// aapt resource value: 0x7F040054
			public const int scrollBar_new_00071 = 2130968660;
			
			// aapt resource value: 0x7F040055
			public const int scrollBar_new_00072 = 2130968661;
			
			// aapt resource value: 0x7F040056
			public const int scrollBar_new_00073 = 2130968662;
			
			// aapt resource value: 0x7F040057
			public const int scrollBar_new_00074 = 2130968663;
			
			// aapt resource value: 0x7F040058
			public const int scrollBar_new_00075 = 2130968664;
			
			// aapt resource value: 0x7F040059
			public const int scrollBar_new_00076 = 2130968665;
			
			// aapt resource value: 0x7F04005A
			public const int scrollBar_new_00077 = 2130968666;
			
			// aapt resource value: 0x7F04005B
			public const int scrollBar_new_00078 = 2130968667;
			
			// aapt resource value: 0x7F04005C
			public const int scrollBar_new_00079 = 2130968668;
			
			// aapt resource value: 0x7F04005D
			public const int scrollBar_new_00080 = 2130968669;
			
			// aapt resource value: 0x7F04005E
			public const int scrollBar_new_00081 = 2130968670;
			
			// aapt resource value: 0x7F04005F
			public const int scrollBar_new_00082 = 2130968671;
			
			// aapt resource value: 0x7F040060
			public const int scrollBar_new_00083 = 2130968672;
			
			// aapt resource value: 0x7F040061
			public const int scrollBar_new_00084 = 2130968673;
			
			// aapt resource value: 0x7F040062
			public const int scrollBar_new_00085 = 2130968674;
			
			// aapt resource value: 0x7F040063
			public const int scrollBar_new_00086 = 2130968675;
			
			// aapt resource value: 0x7F040064
			public const int scrollBar_new_00087 = 2130968676;
			
			// aapt resource value: 0x7F040065
			public const int scrollBar_new_00088 = 2130968677;
			
			// aapt resource value: 0x7F040066
			public const int scrollBar_new_00089 = 2130968678;
			
			// aapt resource value: 0x7F040067
			public const int scrollBar_new_00090 = 2130968679;
			
			// aapt resource value: 0x7F040068
			public const int scrollBar_new_00091 = 2130968680;
			
			// aapt resource value: 0x7F040069
			public const int scrollBar_new_00092 = 2130968681;
			
			// aapt resource value: 0x7F04006A
			public const int scrollBar_new_00093 = 2130968682;
			
			// aapt resource value: 0x7F04006B
			public const int scrollBar_new_00094 = 2130968683;
			
			// aapt resource value: 0x7F04006C
			public const int scrollBar_new_00095 = 2130968684;
			
			// aapt resource value: 0x7F04006D
			public const int scrollBar_new_00096 = 2130968685;
			
			// aapt resource value: 0x7F04006E
			public const int scrollBar_new_00097 = 2130968686;
			
			// aapt resource value: 0x7F04006F
			public const int scrollBar_new_00098 = 2130968687;
			
			// aapt resource value: 0x7F040070
			public const int scrollBar_new_00099 = 2130968688;
			
			// aapt resource value: 0x7F040071
			public const int scrollBar_new_00100 = 2130968689;
			
			// aapt resource value: 0x7F040072
			public const int scrollBar_new_00101 = 2130968690;
			
			// aapt resource value: 0x7F040073
			public const int scrollBar_new_00102 = 2130968691;
			
			// aapt resource value: 0x7F040074
			public const int scrollBar_new_00103 = 2130968692;
			
			// aapt resource value: 0x7F040075
			public const int scrollBar_new_00104 = 2130968693;
			
			// aapt resource value: 0x7F040076
			public const int scrollBar_new_00105 = 2130968694;
			
			// aapt resource value: 0x7F040077
			public const int scrollBar_new_00106 = 2130968695;
			
			// aapt resource value: 0x7F040078
			public const int scrollBar_new_00107 = 2130968696;
			
			// aapt resource value: 0x7F040079
			public const int scrollBar_new_00108 = 2130968697;
			
			// aapt resource value: 0x7F04007A
			public const int scrollBar_new_00109 = 2130968698;
			
			// aapt resource value: 0x7F04007B
			public const int scrollBar_new_00110 = 2130968699;
			
			// aapt resource value: 0x7F04007C
			public const int scrollBar_new_00111 = 2130968700;
			
			// aapt resource value: 0x7F04007D
			public const int scrollBar_new_00112 = 2130968701;
			
			// aapt resource value: 0x7F04007E
			public const int scrollBar_new_00113 = 2130968702;
			
			// aapt resource value: 0x7F04007F
			public const int scrollBar_new_00114 = 2130968703;
			
			// aapt resource value: 0x7F040080
			public const int scrollBar_new_00115 = 2130968704;
			
			// aapt resource value: 0x7F040081
			public const int scrollBar_new_00116 = 2130968705;
			
			// aapt resource value: 0x7F040082
			public const int scrollBar_new_00117 = 2130968706;
			
			// aapt resource value: 0x7F040083
			public const int scrollBar_new_00118 = 2130968707;
			
			// aapt resource value: 0x7F040084
			public const int scrollBar_new_00119 = 2130968708;
			
			// aapt resource value: 0x7F040085
			public const int scrollBar_new_00120 = 2130968709;
			
			// aapt resource value: 0x7F040086
			public const int scrollBar_new_00121 = 2130968710;
			
			// aapt resource value: 0x7F040087
			public const int scrollBar_new_00122 = 2130968711;
			
			// aapt resource value: 0x7F040088
			public const int scrollBar_new_00123 = 2130968712;
			
			// aapt resource value: 0x7F040089
			public const int scrollBar_new_00124 = 2130968713;
			
			// aapt resource value: 0x7F04008A
			public const int scrollBar_new_00125 = 2130968714;
			
			// aapt resource value: 0x7F04008B
			public const int scrollBar_new_00126 = 2130968715;
			
			// aapt resource value: 0x7F04008C
			public const int scrollBar_new_00127 = 2130968716;
			
			// aapt resource value: 0x7F04008D
			public const int scrollBar_new_00128 = 2130968717;
			
			// aapt resource value: 0x7F04008E
			public const int scrollBar_new_00129 = 2130968718;
			
			// aapt resource value: 0x7F04008F
			public const int scrollBar_new_00130 = 2130968719;
			
			// aapt resource value: 0x7F040090
			public const int scrollBar_new_00131 = 2130968720;
			
			// aapt resource value: 0x7F040091
			public const int scrollBar_new_00132 = 2130968721;
			
			// aapt resource value: 0x7F040092
			public const int scrollBar_new_00133 = 2130968722;
			
			// aapt resource value: 0x7F040093
			public const int scrollBar_new_00134 = 2130968723;
			
			// aapt resource value: 0x7F040094
			public const int scrollBar_new_00135 = 2130968724;
			
			// aapt resource value: 0x7F040095
			public const int scrollBar_new_00136 = 2130968725;
			
			// aapt resource value: 0x7F040096
			public const int scrollBar_new_00137 = 2130968726;
			
			// aapt resource value: 0x7F040097
			public const int scrollBar_new_00138 = 2130968727;
			
			// aapt resource value: 0x7F040098
			public const int scrollBar_new_00139 = 2130968728;
			
			// aapt resource value: 0x7F040099
			public const int scrollBar_new_00140 = 2130968729;
			
			// aapt resource value: 0x7F04009A
			public const int scrollBar_new_00141 = 2130968730;
			
			// aapt resource value: 0x7F04009B
			public const int scrollBar_new_00142 = 2130968731;
			
			// aapt resource value: 0x7F04009C
			public const int scrollBar_new_00143 = 2130968732;
			
			// aapt resource value: 0x7F04009D
			public const int scrollBar_new_00144 = 2130968733;
			
			// aapt resource value: 0x7F04009E
			public const int scrollBar_new_00145 = 2130968734;
			
			// aapt resource value: 0x7F04009F
			public const int scrollBar_new_00146 = 2130968735;
			
			// aapt resource value: 0x7F0400A0
			public const int scrollBar_new_00147 = 2130968736;
			
			// aapt resource value: 0x7F0400A1
			public const int scrollBar_new_00148 = 2130968737;
			
			// aapt resource value: 0x7F0400A2
			public const int scrollBar_new_00149 = 2130968738;
			
			// aapt resource value: 0x7F0400A3
			public const int scrollBar_new_00150 = 2130968739;
			
			// aapt resource value: 0x7F0400A4
			public const int scrollBar_new_00151 = 2130968740;
			
			// aapt resource value: 0x7F0400A5
			public const int scrollBar_new_00152 = 2130968741;
			
			// aapt resource value: 0x7F0400A6
			public const int scrollBar_new_00153 = 2130968742;
			
			// aapt resource value: 0x7F0400A7
			public const int scrollBar_new_00154 = 2130968743;
			
			// aapt resource value: 0x7F0400A8
			public const int scrollBar_new_00155 = 2130968744;
			
			// aapt resource value: 0x7F0400A9
			public const int scrollBar_new_00156 = 2130968745;
			
			// aapt resource value: 0x7F0400AA
			public const int scrollBar_new_00157 = 2130968746;
			
			// aapt resource value: 0x7F0400AB
			public const int scrollBar_new_00158 = 2130968747;
			
			// aapt resource value: 0x7F0400AC
			public const int scrollBar_new_00159 = 2130968748;
			
			// aapt resource value: 0x7F0400AD
			public const int scrollBar_new_00160 = 2130968749;
			
			// aapt resource value: 0x7F0400AE
			public const int scrollBar_new_00161 = 2130968750;
			
			// aapt resource value: 0x7F0400AF
			public const int scrollBar_new_00162 = 2130968751;
			
			// aapt resource value: 0x7F0400B0
			public const int scrollBar_new_00163 = 2130968752;
			
			// aapt resource value: 0x7F0400B1
			public const int scrollBar_new_00164 = 2130968753;
			
			// aapt resource value: 0x7F0400B2
			public const int scrollBar_new_00165 = 2130968754;
			
			// aapt resource value: 0x7F0400B3
			public const int scrollBar_new_00166 = 2130968755;
			
			// aapt resource value: 0x7F0400B4
			public const int scrollBar_new_00167 = 2130968756;
			
			// aapt resource value: 0x7F0400B5
			public const int scrollBar_new_00168 = 2130968757;
			
			// aapt resource value: 0x7F0400B6
			public const int scrollBar_new_00169 = 2130968758;
			
			// aapt resource value: 0x7F0400B7
			public const int scrollBar_new_00170 = 2130968759;
			
			// aapt resource value: 0x7F0400B8
			public const int scrollBar_new_00171 = 2130968760;
			
			// aapt resource value: 0x7F0400B9
			public const int scrollBar_new_00172 = 2130968761;
			
			// aapt resource value: 0x7F0400BA
			public const int scrollBar_new_00173 = 2130968762;
			
			// aapt resource value: 0x7F0400BB
			public const int scrollBar_new_00174 = 2130968763;
			
			// aapt resource value: 0x7F0400BC
			public const int scrollBar_new_00175 = 2130968764;
			
			// aapt resource value: 0x7F0400BD
			public const int scrollBar_new_00176 = 2130968765;
			
			// aapt resource value: 0x7F0400BE
			public const int scrollBar_new_00177 = 2130968766;
			
			// aapt resource value: 0x7F0400BF
			public const int scrollBar_new_00178 = 2130968767;
			
			// aapt resource value: 0x7F0400C0
			public const int scrollBar_new_00179 = 2130968768;
			
			// aapt resource value: 0x7F0400C1
			public const int scrollBar_new_00180 = 2130968769;
			
			// aapt resource value: 0x7F0400C2
			public const int scrollBar_new_00181 = 2130968770;
			
			// aapt resource value: 0x7F0400C3
			public const int scrollBar_new_00182 = 2130968771;
			
			// aapt resource value: 0x7F0400C4
			public const int scrollBar_new_00183 = 2130968772;
			
			// aapt resource value: 0x7F0400C5
			public const int scrollBar_new_00184 = 2130968773;
			
			// aapt resource value: 0x7F0400C6
			public const int scrollBar_new_00185 = 2130968774;
			
			// aapt resource value: 0x7F0400C7
			public const int scrollBar_new_00186 = 2130968775;
			
			// aapt resource value: 0x7F0400C8
			public const int scrollBar_new_00187 = 2130968776;
			
			// aapt resource value: 0x7F0400C9
			public const int scrollBar_new_00188 = 2130968777;
			
			// aapt resource value: 0x7F0400CA
			public const int scrollBar_new_00189 = 2130968778;
			
			// aapt resource value: 0x7F0400CB
			public const int scrollBar_new_00190 = 2130968779;
			
			// aapt resource value: 0x7F0400CC
			public const int scrollBar_new_00191 = 2130968780;
			
			// aapt resource value: 0x7F0400CD
			public const int scrollBar_new_00192 = 2130968781;
			
			// aapt resource value: 0x7F0400CE
			public const int scrollBar_new_00193 = 2130968782;
			
			// aapt resource value: 0x7F0400CF
			public const int scrollBar_new_00194 = 2130968783;
			
			// aapt resource value: 0x7F0400D0
			public const int scrollBar_new_00195 = 2130968784;
			
			// aapt resource value: 0x7F0400D1
			public const int scrollBar_new_00196 = 2130968785;
			
			// aapt resource value: 0x7F0400D2
			public const int scrollBar_new_00197 = 2130968786;
			
			// aapt resource value: 0x7F0400D3
			public const int scrollBar_new_00198 = 2130968787;
			
			// aapt resource value: 0x7F0400D4
			public const int scrollBar_new_00199 = 2130968788;
			
			// aapt resource value: 0x7F0400D5
			public const int scrollBar_new_00200 = 2130968789;
			
			// aapt resource value: 0x7F0400D6
			public const int scrollBar_new_00201 = 2130968790;
			
			// aapt resource value: 0x7F0400D7
			public const int scrollBar_new_00202 = 2130968791;
			
			// aapt resource value: 0x7F0400D8
			public const int scrollBar_new_00203 = 2130968792;
			
			// aapt resource value: 0x7F0400D9
			public const int scrollBar_new_00204 = 2130968793;
			
			// aapt resource value: 0x7F0400DA
			public const int scrollBar_new_00205 = 2130968794;
			
			// aapt resource value: 0x7F0400DB
			public const int scrollBar_new_00206 = 2130968795;
			
			// aapt resource value: 0x7F0400DC
			public const int scrollBar_new_00207 = 2130968796;
			
			// aapt resource value: 0x7F0400DD
			public const int scrollBar_new_00208 = 2130968797;
			
			// aapt resource value: 0x7F0400DE
			public const int scrollBar_new_00209 = 2130968798;
			
			// aapt resource value: 0x7F0400DF
			public const int scrollBar_new_00210 = 2130968799;
			
			// aapt resource value: 0x7F0400E0
			public const int scrollBar_new_00211 = 2130968800;
			
			// aapt resource value: 0x7F0400E1
			public const int scrollBar_new_00212 = 2130968801;
			
			// aapt resource value: 0x7F0400E2
			public const int scrollBar_new_00213 = 2130968802;
			
			// aapt resource value: 0x7F0400E3
			public const int scrollBar_new_00214 = 2130968803;
			
			// aapt resource value: 0x7F0400E4
			public const int scrollBar_new_00215 = 2130968804;
			
			// aapt resource value: 0x7F0400E5
			public const int scrollBar_new_00216 = 2130968805;
			
			// aapt resource value: 0x7F0400E6
			public const int scrollBar_new_00217 = 2130968806;
			
			// aapt resource value: 0x7F0400E7
			public const int scrollBar_new_00218 = 2130968807;
			
			// aapt resource value: 0x7F0400E8
			public const int scrollBar_new_00219 = 2130968808;
			
			// aapt resource value: 0x7F0400E9
			public const int scrollBar_new_00220 = 2130968809;
			
			// aapt resource value: 0x7F0400EA
			public const int scrollBar_new_00221 = 2130968810;
			
			// aapt resource value: 0x7F0400EB
			public const int scrollBar_new_00222 = 2130968811;
			
			// aapt resource value: 0x7F0400EC
			public const int scrollBar_new_00223 = 2130968812;
			
			// aapt resource value: 0x7F0400ED
			public const int scrollBar_new_00224 = 2130968813;
			
			// aapt resource value: 0x7F0400EE
			public const int scrollBar_new_00225 = 2130968814;
			
			// aapt resource value: 0x7F0400EF
			public const int scrollBar_new_00226 = 2130968815;
			
			// aapt resource value: 0x7F0400F0
			public const int scrollBar_new_00227 = 2130968816;
			
			// aapt resource value: 0x7F0400F1
			public const int scrollBar_new_00228 = 2130968817;
			
			// aapt resource value: 0x7F0400F2
			public const int scrollBar_new_00229 = 2130968818;
			
			// aapt resource value: 0x7F0400F3
			public const int scrollBar_new_00230 = 2130968819;
			
			// aapt resource value: 0x7F0400F4
			public const int scrollBar_new_00231 = 2130968820;
			
			// aapt resource value: 0x7F0400F5
			public const int scrollBar_new_00232 = 2130968821;
			
			// aapt resource value: 0x7F0400F6
			public const int scrollBar_new_00233 = 2130968822;
			
			// aapt resource value: 0x7F0400F7
			public const int scrollBar_new_00234 = 2130968823;
			
			// aapt resource value: 0x7F0400F8
			public const int scrollBar_new_00235 = 2130968824;
			
			// aapt resource value: 0x7F0400F9
			public const int scrollBar_new_00236 = 2130968825;
			
			// aapt resource value: 0x7F0400FA
			public const int scrollBar_new_00237 = 2130968826;
			
			// aapt resource value: 0x7F0400FB
			public const int scrollBar_new_00238 = 2130968827;
			
			// aapt resource value: 0x7F0400FC
			public const int scrollBar_new_00239 = 2130968828;
			
			// aapt resource value: 0x7F0400FD
			public const int scrollBar_new_00240 = 2130968829;
			
			// aapt resource value: 0x7F0400FE
			public const int scrollBar_new_00241 = 2130968830;
			
			// aapt resource value: 0x7F0400FF
			public const int scrollBar_new_00242 = 2130968831;
			
			// aapt resource value: 0x7F040100
			public const int scrollBar_new_00243 = 2130968832;
			
			// aapt resource value: 0x7F040101
			public const int scrollBar_new_00244 = 2130968833;
			
			// aapt resource value: 0x7F040102
			public const int scrollBar_new_00245 = 2130968834;
			
			// aapt resource value: 0x7F040103
			public const int scrollBar_new_00246 = 2130968835;
			
			// aapt resource value: 0x7F040104
			public const int scrollBar_new_00247 = 2130968836;
			
			// aapt resource value: 0x7F040105
			public const int scrollBar_new_00248 = 2130968837;
			
			// aapt resource value: 0x7F040106
			public const int scrollBar_new_00249 = 2130968838;
			
			// aapt resource value: 0x7F040107
			public const int scrollBar_new_00250 = 2130968839;
			
			// aapt resource value: 0x7F040108
			public const int scrollBar_new_00251 = 2130968840;
			
			// aapt resource value: 0x7F040109
			public const int scrollBar_new_00252 = 2130968841;
			
			// aapt resource value: 0x7F04010A
			public const int scrollBar_new_00253 = 2130968842;
			
			// aapt resource value: 0x7F04010B
			public const int scrollBar_new_00254 = 2130968843;
			
			// aapt resource value: 0x7F04010C
			public const int scrollBar_new_00255 = 2130968844;
			
			// aapt resource value: 0x7F04010D
			public const int scrollBar_new_00256 = 2130968845;
			
			// aapt resource value: 0x7F04010E
			public const int scrollBar_new_00257 = 2130968846;
			
			// aapt resource value: 0x7F04010F
			public const int scrollBar_new_00258 = 2130968847;
			
			// aapt resource value: 0x7F040110
			public const int scrollBar_new_00259 = 2130968848;
			
			// aapt resource value: 0x7F040111
			public const int scrollBar_new_00260 = 2130968849;
			
			// aapt resource value: 0x7F040112
			public const int scrollBar_new_00261 = 2130968850;
			
			// aapt resource value: 0x7F040113
			public const int scrollBar_new_00262 = 2130968851;
			
			// aapt resource value: 0x7F040114
			public const int scrollBar_new_00263 = 2130968852;
			
			// aapt resource value: 0x7F040115
			public const int scrollBar_new_00264 = 2130968853;
			
			// aapt resource value: 0x7F040116
			public const int scrollBar_new_00265 = 2130968854;
			
			// aapt resource value: 0x7F040117
			public const int scrollBar_new_00266 = 2130968855;
			
			// aapt resource value: 0x7F040118
			public const int scrollBar_new_00267 = 2130968856;
			
			// aapt resource value: 0x7F040119
			public const int scrollBar_new_00268 = 2130968857;
			
			// aapt resource value: 0x7F04011A
			public const int scrollBar_new_00269 = 2130968858;
			
			// aapt resource value: 0x7F04011B
			public const int scrollBar_new_00270 = 2130968859;
			
			// aapt resource value: 0x7F04011C
			public const int scrollBar_new_00271 = 2130968860;
			
			// aapt resource value: 0x7F04011D
			public const int scrollBar_new_00272 = 2130968861;
			
			// aapt resource value: 0x7F04011E
			public const int scrollBar_new_00273 = 2130968862;
			
			// aapt resource value: 0x7F04011F
			public const int scrollBar_new_00274 = 2130968863;
			
			// aapt resource value: 0x7F040120
			public const int scrollBar_new_00275 = 2130968864;
			
			// aapt resource value: 0x7F040121
			public const int scrollBar_new_00276 = 2130968865;
			
			// aapt resource value: 0x7F040122
			public const int scrollBar_new_00277 = 2130968866;
			
			// aapt resource value: 0x7F040123
			public const int scrollBar_new_00278 = 2130968867;
			
			// aapt resource value: 0x7F040124
			public const int scrollBar_new_00279 = 2130968868;
			
			// aapt resource value: 0x7F040125
			public const int scrollBar_new_00280 = 2130968869;
			
			// aapt resource value: 0x7F040126
			public const int scrollBar_new_00281 = 2130968870;
			
			// aapt resource value: 0x7F040127
			public const int scrollBar_new_00282 = 2130968871;
			
			// aapt resource value: 0x7F040128
			public const int scrollBar_new_00283 = 2130968872;
			
			// aapt resource value: 0x7F040129
			public const int scrollBar_new_00284 = 2130968873;
			
			// aapt resource value: 0x7F04012A
			public const int scrollBar_new_00285 = 2130968874;
			
			// aapt resource value: 0x7F04012B
			public const int scrollBar_new_00286 = 2130968875;
			
			// aapt resource value: 0x7F04012C
			public const int scrollBar_new_00287 = 2130968876;
			
			// aapt resource value: 0x7F04012D
			public const int scrollBar_new_00288 = 2130968877;
			
			// aapt resource value: 0x7F04012E
			public const int scrollBar_new_00289 = 2130968878;
			
			// aapt resource value: 0x7F04012F
			public const int scrollBar_new_00290 = 2130968879;
			
			// aapt resource value: 0x7F040130
			public const int scrollBar_new_00291 = 2130968880;
			
			// aapt resource value: 0x7F040131
			public const int scrollBar_new_00292 = 2130968881;
			
			// aapt resource value: 0x7F040132
			public const int scrollBar_new_00293 = 2130968882;
			
			// aapt resource value: 0x7F040133
			public const int scrollBar_new_00294 = 2130968883;
			
			// aapt resource value: 0x7F040134
			public const int scrollBar_new_00295 = 2130968884;
			
			// aapt resource value: 0x7F040135
			public const int scrollBar_new_00296 = 2130968885;
			
			// aapt resource value: 0x7F040136
			public const int scrollBar_new_00297 = 2130968886;
			
			// aapt resource value: 0x7F040137
			public const int scrollBar_new_00298 = 2130968887;
			
			// aapt resource value: 0x7F040138
			public const int scrollBar_new_00299 = 2130968888;
			
			// aapt resource value: 0x7F040139
			public const int scrollBar_new_00300 = 2130968889;
			
			// aapt resource value: 0x7F04013A
			public const int scrollBar_new_00301 = 2130968890;
			
			// aapt resource value: 0x7F04013B
			public const int scrollBar_new_00302 = 2130968891;
			
			// aapt resource value: 0x7F04013C
			public const int scrollBar_new_00303 = 2130968892;
			
			// aapt resource value: 0x7F04013D
			public const int scrollBar_new_00304 = 2130968893;
			
			// aapt resource value: 0x7F04013E
			public const int scrollBar_new_00305 = 2130968894;
			
			// aapt resource value: 0x7F04013F
			public const int scrollBar_new_00306 = 2130968895;
			
			// aapt resource value: 0x7F040140
			public const int scrollBar_new_00307 = 2130968896;
			
			// aapt resource value: 0x7F040141
			public const int scrollBar_new_00308 = 2130968897;
			
			// aapt resource value: 0x7F040142
			public const int scrollBar_new_00309 = 2130968898;
			
			// aapt resource value: 0x7F040143
			public const int scrollBar_new_00310 = 2130968899;
			
			// aapt resource value: 0x7F040144
			public const int scrollBar_new_00311 = 2130968900;
			
			// aapt resource value: 0x7F040145
			public const int scrollBar_new_00312 = 2130968901;
			
			// aapt resource value: 0x7F040146
			public const int scrollBar_new_00313 = 2130968902;
			
			// aapt resource value: 0x7F040147
			public const int scrollBar_new_00314 = 2130968903;
			
			// aapt resource value: 0x7F040148
			public const int scrollBar_new_00315 = 2130968904;
			
			// aapt resource value: 0x7F040149
			public const int scrollBar_new_00316 = 2130968905;
			
			// aapt resource value: 0x7F04014A
			public const int scrollBar_new_00317 = 2130968906;
			
			// aapt resource value: 0x7F04014B
			public const int scrollBar_new_00318 = 2130968907;
			
			// aapt resource value: 0x7F04014C
			public const int scrollBar_new_00319 = 2130968908;
			
			// aapt resource value: 0x7F04014D
			public const int scrollBar_new_00320 = 2130968909;
			
			// aapt resource value: 0x7F04014E
			public const int scrollBar_new_00321 = 2130968910;
			
			// aapt resource value: 0x7F04014F
			public const int scrollBar_new_00322 = 2130968911;
			
			// aapt resource value: 0x7F040150
			public const int scrollBar_new_00323 = 2130968912;
			
			// aapt resource value: 0x7F040151
			public const int scrollBar_new_00324 = 2130968913;
			
			// aapt resource value: 0x7F040152
			public const int scrollBar_new_00325 = 2130968914;
			
			// aapt resource value: 0x7F040153
			public const int scrollBar_new_00326 = 2130968915;
			
			// aapt resource value: 0x7F040154
			public const int scrollBar_new_00327 = 2130968916;
			
			// aapt resource value: 0x7F040155
			public const int scrollBar_new_00328 = 2130968917;
			
			// aapt resource value: 0x7F040156
			public const int scrollBar_new_00329 = 2130968918;
			
			// aapt resource value: 0x7F040157
			public const int scrollBar_new_00330 = 2130968919;
			
			// aapt resource value: 0x7F040158
			public const int scrollBar_new_00331 = 2130968920;
			
			// aapt resource value: 0x7F040159
			public const int scrollBar_new_00332 = 2130968921;
			
			// aapt resource value: 0x7F04015A
			public const int scrollBar_new_00333 = 2130968922;
			
			// aapt resource value: 0x7F04015B
			public const int scrollBar_new_00334 = 2130968923;
			
			// aapt resource value: 0x7F04015C
			public const int scrollBar_new_00335 = 2130968924;
			
			// aapt resource value: 0x7F04015D
			public const int scrollBar_new_00336 = 2130968925;
			
			// aapt resource value: 0x7F04015E
			public const int scrollBar_new_00337 = 2130968926;
			
			// aapt resource value: 0x7F04015F
			public const int scrollBar_new_00338 = 2130968927;
			
			// aapt resource value: 0x7F040160
			public const int scrollBar_new_00339 = 2130968928;
			
			// aapt resource value: 0x7F040161
			public const int scrollBar_new_00340 = 2130968929;
			
			// aapt resource value: 0x7F040162
			public const int scrollBar_new_00341 = 2130968930;
			
			// aapt resource value: 0x7F040163
			public const int scrollBar_new_00342 = 2130968931;
			
			// aapt resource value: 0x7F040164
			public const int scrollBar_new_00343 = 2130968932;
			
			// aapt resource value: 0x7F040165
			public const int scrollBar_new_00344 = 2130968933;
			
			// aapt resource value: 0x7F040166
			public const int scrollBar_new_00345 = 2130968934;
			
			// aapt resource value: 0x7F040167
			public const int scrollBar_new_00346 = 2130968935;
			
			// aapt resource value: 0x7F040168
			public const int scrollBar_new_00347 = 2130968936;
			
			// aapt resource value: 0x7F040169
			public const int scrollBar_new_00348 = 2130968937;
			
			// aapt resource value: 0x7F04016A
			public const int scrollBar_new_00349 = 2130968938;
			
			// aapt resource value: 0x7F04016B
			public const int scrollBar_new_00350 = 2130968939;
			
			// aapt resource value: 0x7F04016C
			public const int scrollBar_new_00351 = 2130968940;
			
			// aapt resource value: 0x7F04016D
			public const int scrollBar_new_00352 = 2130968941;
			
			// aapt resource value: 0x7F04016E
			public const int scrollBar_new_00353 = 2130968942;
			
			// aapt resource value: 0x7F04016F
			public const int scrollBar_new_00354 = 2130968943;
			
			// aapt resource value: 0x7F040170
			public const int scrollBar_new_00355 = 2130968944;
			
			// aapt resource value: 0x7F040171
			public const int scrollBar_new_00356 = 2130968945;
			
			// aapt resource value: 0x7F040172
			public const int scrollBar_new_00357 = 2130968946;
			
			// aapt resource value: 0x7F040173
			public const int scrollBar_new_00358 = 2130968947;
			
			// aapt resource value: 0x7F040174
			public const int scrollBar_new_00359 = 2130968948;
			
			// aapt resource value: 0x7F040175
			public const int scrollBar_new_00360 = 2130968949;
			
			// aapt resource value: 0x7F040176
			public const int scrollBar_new_00361 = 2130968950;
			
			// aapt resource value: 0x7F040177
			public const int scrollBar_new_00362 = 2130968951;
			
			// aapt resource value: 0x7F040178
			public const int scrollBar_new_00363 = 2130968952;
			
			// aapt resource value: 0x7F040179
			public const int scrollBar_new_00364 = 2130968953;
			
			// aapt resource value: 0x7F04017A
			public const int scrollBar_new_00365 = 2130968954;
			
			// aapt resource value: 0x7F04017B
			public const int scrollBar_new_00366 = 2130968955;
			
			// aapt resource value: 0x7F04017C
			public const int scrollBar_new_00367 = 2130968956;
			
			// aapt resource value: 0x7F04017D
			public const int scrollBar_new_00368 = 2130968957;
			
			// aapt resource value: 0x7F04017E
			public const int scrollBar_new_00369 = 2130968958;
			
			// aapt resource value: 0x7F04017F
			public const int scrollBar_new_00370 = 2130968959;
			
			// aapt resource value: 0x7F040180
			public const int scrollBar_new_00371 = 2130968960;
			
			// aapt resource value: 0x7F040181
			public const int scrollBar_new_00372 = 2130968961;
			
			// aapt resource value: 0x7F040182
			public const int scrollBar_new_00373 = 2130968962;
			
			// aapt resource value: 0x7F040183
			public const int scrollBar_new_00374 = 2130968963;
			
			// aapt resource value: 0x7F040184
			public const int scrollBar_new_00375 = 2130968964;
			
			// aapt resource value: 0x7F040185
			public const int scrollBar_new_00376 = 2130968965;
			
			// aapt resource value: 0x7F040186
			public const int scrollBar_new_00377 = 2130968966;
			
			// aapt resource value: 0x7F040187
			public const int scrollBar_new_00378 = 2130968967;
			
			// aapt resource value: 0x7F040188
			public const int scrollBar_new_00379 = 2130968968;
			
			// aapt resource value: 0x7F040189
			public const int scrollBar_new_00380 = 2130968969;
			
			// aapt resource value: 0x7F04018A
			public const int scrollBar_new_00381 = 2130968970;
			
			// aapt resource value: 0x7F04018B
			public const int scrollBar_new_00382 = 2130968971;
			
			// aapt resource value: 0x7F04018C
			public const int scrollBar_new_00383 = 2130968972;
			
			// aapt resource value: 0x7F04018D
			public const int scrollBar_new_00384 = 2130968973;
			
			// aapt resource value: 0x7F04018E
			public const int scrollBar_new_00385 = 2130968974;
			
			// aapt resource value: 0x7F04018F
			public const int scrollBar_new_00386 = 2130968975;
			
			// aapt resource value: 0x7F040190
			public const int scrollBar_new_00387 = 2130968976;
			
			// aapt resource value: 0x7F040191
			public const int scrollBar_new_00388 = 2130968977;
			
			// aapt resource value: 0x7F040192
			public const int scrollBar_new_00389 = 2130968978;
			
			// aapt resource value: 0x7F040193
			public const int scrollBar_new_00390 = 2130968979;
			
			// aapt resource value: 0x7F040194
			public const int scrollBar_new_00391 = 2130968980;
			
			// aapt resource value: 0x7F040195
			public const int scrollBar_new_00392 = 2130968981;
			
			// aapt resource value: 0x7F040196
			public const int scrollBar_new_00393 = 2130968982;
			
			// aapt resource value: 0x7F040197
			public const int scrollBar_new_00394 = 2130968983;
			
			// aapt resource value: 0x7F040198
			public const int scrollBar_new_00395 = 2130968984;
			
			// aapt resource value: 0x7F040199
			public const int scrollBar_new_00396 = 2130968985;
			
			// aapt resource value: 0x7F04019A
			public const int scrollBar_new_00397 = 2130968986;
			
			// aapt resource value: 0x7F04019B
			public const int scrollBar_new_00398 = 2130968987;
			
			// aapt resource value: 0x7F04019C
			public const int scrollBar_new_00399 = 2130968988;
			
			// aapt resource value: 0x7F04019D
			public const int scrollBar_new_00400 = 2130968989;
			
			// aapt resource value: 0x7F04019E
			public const int scrollBar_new_00401 = 2130968990;
			
			// aapt resource value: 0x7F04019F
			public const int scrollBar_new_00402 = 2130968991;
			
			// aapt resource value: 0x7F0401A0
			public const int scrollBar_new_00403 = 2130968992;
			
			// aapt resource value: 0x7F0401A1
			public const int scrollBar_new_00404 = 2130968993;
			
			// aapt resource value: 0x7F0401A2
			public const int scrollBar_new_00405 = 2130968994;
			
			// aapt resource value: 0x7F0401A3
			public const int scrollBar_new_00406 = 2130968995;
			
			// aapt resource value: 0x7F0401A4
			public const int scrollBar_new_00407 = 2130968996;
			
			// aapt resource value: 0x7F0401A5
			public const int scrollBar_new_00408 = 2130968997;
			
			// aapt resource value: 0x7F0401A6
			public const int scrollBar_new_00409 = 2130968998;
			
			// aapt resource value: 0x7F0401A7
			public const int scrollBar_new_00410 = 2130968999;
			
			// aapt resource value: 0x7F0401A8
			public const int scrollBar_new_00411 = 2130969000;
			
			// aapt resource value: 0x7F0401A9
			public const int scrollBar_new_00412 = 2130969001;
			
			// aapt resource value: 0x7F0401AA
			public const int scrollBar_new_00413 = 2130969002;
			
			// aapt resource value: 0x7F0401AB
			public const int scrollBar_new_00414 = 2130969003;
			
			// aapt resource value: 0x7F0401AC
			public const int scrollBar_new_00415 = 2130969004;
			
			// aapt resource value: 0x7F0401AD
			public const int scrollBar_new_00416 = 2130969005;
			
			// aapt resource value: 0x7F0401AE
			public const int scrollBar_new_00417 = 2130969006;
			
			// aapt resource value: 0x7F0401AF
			public const int scrollBar_new_00418 = 2130969007;
			
			// aapt resource value: 0x7F0401B0
			public const int scrollBar_new_00419 = 2130969008;
			
			// aapt resource value: 0x7F0401B1
			public const int scrollBar_new_00420 = 2130969009;
			
			// aapt resource value: 0x7F0401B2
			public const int scrollBar_new_00421 = 2130969010;
			
			// aapt resource value: 0x7F0401B3
			public const int scrollBar_new_00422 = 2130969011;
			
			// aapt resource value: 0x7F0401B4
			public const int scrollBar_new_00423 = 2130969012;
			
			// aapt resource value: 0x7F0401B5
			public const int scrollBar_new_00424 = 2130969013;
			
			// aapt resource value: 0x7F0401B6
			public const int scrollBar_new_00425 = 2130969014;
			
			// aapt resource value: 0x7F0401B7
			public const int scrollBar_new_00426 = 2130969015;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F050000
			public const int accessibility_action_clickable_span = 2131034112;
			
			// aapt resource value: 0x7F050001
			public const int accessibility_custom_action_0 = 2131034113;
			
			// aapt resource value: 0x7F050002
			public const int accessibility_custom_action_1 = 2131034114;
			
			// aapt resource value: 0x7F050003
			public const int accessibility_custom_action_10 = 2131034115;
			
			// aapt resource value: 0x7F050004
			public const int accessibility_custom_action_11 = 2131034116;
			
			// aapt resource value: 0x7F050005
			public const int accessibility_custom_action_12 = 2131034117;
			
			// aapt resource value: 0x7F050006
			public const int accessibility_custom_action_13 = 2131034118;
			
			// aapt resource value: 0x7F050007
			public const int accessibility_custom_action_14 = 2131034119;
			
			// aapt resource value: 0x7F050008
			public const int accessibility_custom_action_15 = 2131034120;
			
			// aapt resource value: 0x7F050009
			public const int accessibility_custom_action_16 = 2131034121;
			
			// aapt resource value: 0x7F05000A
			public const int accessibility_custom_action_17 = 2131034122;
			
			// aapt resource value: 0x7F05000B
			public const int accessibility_custom_action_18 = 2131034123;
			
			// aapt resource value: 0x7F05000C
			public const int accessibility_custom_action_19 = 2131034124;
			
			// aapt resource value: 0x7F05000D
			public const int accessibility_custom_action_2 = 2131034125;
			
			// aapt resource value: 0x7F05000E
			public const int accessibility_custom_action_20 = 2131034126;
			
			// aapt resource value: 0x7F05000F
			public const int accessibility_custom_action_21 = 2131034127;
			
			// aapt resource value: 0x7F050010
			public const int accessibility_custom_action_22 = 2131034128;
			
			// aapt resource value: 0x7F050011
			public const int accessibility_custom_action_23 = 2131034129;
			
			// aapt resource value: 0x7F050012
			public const int accessibility_custom_action_24 = 2131034130;
			
			// aapt resource value: 0x7F050013
			public const int accessibility_custom_action_25 = 2131034131;
			
			// aapt resource value: 0x7F050014
			public const int accessibility_custom_action_26 = 2131034132;
			
			// aapt resource value: 0x7F050015
			public const int accessibility_custom_action_27 = 2131034133;
			
			// aapt resource value: 0x7F050016
			public const int accessibility_custom_action_28 = 2131034134;
			
			// aapt resource value: 0x7F050017
			public const int accessibility_custom_action_29 = 2131034135;
			
			// aapt resource value: 0x7F050018
			public const int accessibility_custom_action_3 = 2131034136;
			
			// aapt resource value: 0x7F050019
			public const int accessibility_custom_action_30 = 2131034137;
			
			// aapt resource value: 0x7F05001A
			public const int accessibility_custom_action_31 = 2131034138;
			
			// aapt resource value: 0x7F05001B
			public const int accessibility_custom_action_4 = 2131034139;
			
			// aapt resource value: 0x7F05001C
			public const int accessibility_custom_action_5 = 2131034140;
			
			// aapt resource value: 0x7F05001D
			public const int accessibility_custom_action_6 = 2131034141;
			
			// aapt resource value: 0x7F05001E
			public const int accessibility_custom_action_7 = 2131034142;
			
			// aapt resource value: 0x7F05001F
			public const int accessibility_custom_action_8 = 2131034143;
			
			// aapt resource value: 0x7F050020
			public const int accessibility_custom_action_9 = 2131034144;
			
			// aapt resource value: 0x7F050025
			public const int actions = 2131034149;
			
			// aapt resource value: 0x7F050021
			public const int action_container = 2131034145;
			
			// aapt resource value: 0x7F050022
			public const int action_divider = 2131034146;
			
			// aapt resource value: 0x7F050023
			public const int action_image = 2131034147;
			
			// aapt resource value: 0x7F050024
			public const int action_text = 2131034148;
			
			// aapt resource value: 0x7F050026
			public const int async = 2131034150;
			
			// aapt resource value: 0x7F050027
			public const int blocking = 2131034151;
			
			// aapt resource value: 0x7F050028
			public const int chronometer = 2131034152;
			
			// aapt resource value: 0x7F050029
			public const int dialog_button = 2131034153;
			
			// aapt resource value: 0x7F05002A
			public const int forever = 2131034154;
			
			// aapt resource value: 0x7F05002B
			public const int icon = 2131034155;
			
			// aapt resource value: 0x7F05002C
			public const int icon_group = 2131034156;
			
			// aapt resource value: 0x7F05002D
			public const int imageView = 2131034157;
			
			// aapt resource value: 0x7F05002E
			public const int info = 2131034158;
			
			// aapt resource value: 0x7F05002F
			public const int italic = 2131034159;
			
			// aapt resource value: 0x7F050030
			public const int item_touch_helper_previous_elevation = 2131034160;
			
			// aapt resource value: 0x7F050031
			public const int line1 = 2131034161;
			
			// aapt resource value: 0x7F050032
			public const int line3 = 2131034162;
			
			// aapt resource value: 0x7F050033
			public const int normal = 2131034163;
			
			// aapt resource value: 0x7F050034
			public const int notification_background = 2131034164;
			
			// aapt resource value: 0x7F050035
			public const int notification_main_column = 2131034165;
			
			// aapt resource value: 0x7F050036
			public const int notification_main_column_container = 2131034166;
			
			// aapt resource value: 0x7F050037
			public const int recyclerView = 2131034167;
			
			// aapt resource value: 0x7F050038
			public const int right_icon = 2131034168;
			
			// aapt resource value: 0x7F050039
			public const int right_side = 2131034169;
			
			// aapt resource value: 0x7F05003A
			public const int tag_accessibility_actions = 2131034170;
			
			// aapt resource value: 0x7F05003B
			public const int tag_accessibility_clickable_spans = 2131034171;
			
			// aapt resource value: 0x7F05003C
			public const int tag_accessibility_heading = 2131034172;
			
			// aapt resource value: 0x7F05003D
			public const int tag_accessibility_pane_title = 2131034173;
			
			// aapt resource value: 0x7F05003E
			public const int tag_on_apply_window_listener = 2131034174;
			
			// aapt resource value: 0x7F05003F
			public const int tag_on_receive_content_listener = 2131034175;
			
			// aapt resource value: 0x7F050040
			public const int tag_on_receive_content_mime_types = 2131034176;
			
			// aapt resource value: 0x7F050041
			public const int tag_screen_reader_focusable = 2131034177;
			
			// aapt resource value: 0x7F050042
			public const int tag_state_description = 2131034178;
			
			// aapt resource value: 0x7F050043
			public const int tag_transition_group = 2131034179;
			
			// aapt resource value: 0x7F050044
			public const int tag_unhandled_key_event_manager = 2131034180;
			
			// aapt resource value: 0x7F050045
			public const int tag_unhandled_key_listeners = 2131034181;
			
			// aapt resource value: 0x7F050046
			public const int tag_window_insets_animation_callback = 2131034182;
			
			// aapt resource value: 0x7F050047
			public const int text = 2131034183;
			
			// aapt resource value: 0x7F050048
			public const int text2 = 2131034184;
			
			// aapt resource value: 0x7F050049
			public const int time = 2131034185;
			
			// aapt resource value: 0x7F05004A
			public const int title = 2131034186;
			
			// aapt resource value: 0x7F05004B
			public const int view_tree_lifecycle_owner = 2131034187;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7F060000
			public const int status_bar_notification_info_maxnum = 2131099648;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F070000
			public const int custom_dialog = 2131165184;
			
			// aapt resource value: 0x7F070001
			public const int ImageCardView = 2131165185;
			
			// aapt resource value: 0x7F070002
			public const int Main = 2131165186;
			
			// aapt resource value: 0x7F070003
			public const int notification_action = 2131165187;
			
			// aapt resource value: 0x7F070004
			public const int notification_action_tombstone = 2131165188;
			
			// aapt resource value: 0x7F070005
			public const int notification_template_custom_big = 2131165189;
			
			// aapt resource value: 0x7F070006
			public const int notification_template_icon_group = 2131165190;
			
			// aapt resource value: 0x7F070007
			public const int notification_template_part_chronometer = 2131165191;
			
			// aapt resource value: 0x7F070008
			public const int notification_template_part_time = 2131165192;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F080000
			public const int ApplicationName = 2131230720;
			
			// aapt resource value: 0x7F080001
			public const int Hello = 2131230721;
			
			// aapt resource value: 0x7F080002
			public const int status_bar_notification_info_overflow = 2131230722;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F090000
			public const int TextAppearance_Compat_Notification = 2131296256;
			
			// aapt resource value: 0x7F090001
			public const int TextAppearance_Compat_Notification_Info = 2131296257;
			
			// aapt resource value: 0x7F090002
			public const int TextAppearance_Compat_Notification_Line2 = 2131296258;
			
			// aapt resource value: 0x7F090003
			public const int TextAppearance_Compat_Notification_Time = 2131296259;
			
			// aapt resource value: 0x7F090004
			public const int TextAppearance_Compat_Notification_Title = 2131296260;
			
			// aapt resource value: 0x7F090005
			public const int Widget_Compat_NotificationActionContainer = 2131296261;
			
			// aapt resource value: 0x7F090006
			public const int Widget_Compat_NotificationActionText = 2131296262;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			// aapt resource value: { 0x10101A5,0x101031F,0x7F010000 }
			public static int[] ColorStateListItem = new int[] {
					16843173,
					16843551,
					2130771968};
			
			// aapt resource value: 2
			public const int ColorStateListItem_alpha = 2;
			
			// aapt resource value: 1
			public const int ColorStateListItem_android_alpha = 1;
			
			// aapt resource value: 0
			public const int ColorStateListItem_android_color = 0;
			
			// aapt resource value: { 0x7F010007,0x7F010008,0x7F010009,0x7F01000A,0x7F01000B,0x7F01000C,0x7F01000D }
			public static int[] FontFamily = new int[] {
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981};
			
			// aapt resource value: { 0x1010532,0x1010533,0x101053F,0x101056F,0x1010570,0x7F010006,0x7F01000E,0x7F01000F,0x7F010010,0x7F010016 }
			public static int[] FontFamilyFont = new int[] {
					16844082,
					16844083,
					16844095,
					16844143,
					16844144,
					2130771974,
					2130771982,
					2130771983,
					2130771984,
					2130771990};
			
			// aapt resource value: 0
			public const int FontFamilyFont_android_font = 0;
			
			// aapt resource value: 2
			public const int FontFamilyFont_android_fontStyle = 2;
			
			// aapt resource value: 4
			public const int FontFamilyFont_android_fontVariationSettings = 4;
			
			// aapt resource value: 1
			public const int FontFamilyFont_android_fontWeight = 1;
			
			// aapt resource value: 3
			public const int FontFamilyFont_android_ttcIndex = 3;
			
			// aapt resource value: 5
			public const int FontFamilyFont_font = 5;
			
			// aapt resource value: 6
			public const int FontFamilyFont_fontStyle = 6;
			
			// aapt resource value: 7
			public const int FontFamilyFont_fontVariationSettings = 7;
			
			// aapt resource value: 8
			public const int FontFamilyFont_fontWeight = 8;
			
			// aapt resource value: 9
			public const int FontFamilyFont_ttcIndex = 9;
			
			// aapt resource value: 0
			public const int FontFamily_fontProviderAuthority = 0;
			
			// aapt resource value: 1
			public const int FontFamily_fontProviderCerts = 1;
			
			// aapt resource value: 2
			public const int FontFamily_fontProviderFetchStrategy = 2;
			
			// aapt resource value: 3
			public const int FontFamily_fontProviderFetchTimeout = 3;
			
			// aapt resource value: 4
			public const int FontFamily_fontProviderPackage = 4;
			
			// aapt resource value: 5
			public const int FontFamily_fontProviderQuery = 5;
			
			// aapt resource value: 6
			public const int FontFamily_fontProviderSystemFontFamily = 6;
			
			// aapt resource value: { 0x101019D,0x101019E,0x10101A1,0x10101A2,0x10101A3,0x10101A4,0x1010201,0x101020B,0x1010510,0x1010511,0x1010512,0x1010513 }
			public static int[] GradientColor = new int[] {
					16843165,
					16843166,
					16843169,
					16843170,
					16843171,
					16843172,
					16843265,
					16843275,
					16844048,
					16844049,
					16844050,
					16844051};
			
			// aapt resource value: { 0x10101A5,0x1010514 }
			public static int[] GradientColorItem = new int[] {
					16843173,
					16844052};
			
			// aapt resource value: 0
			public const int GradientColorItem_android_color = 0;
			
			// aapt resource value: 1
			public const int GradientColorItem_android_offset = 1;
			
			// aapt resource value: 7
			public const int GradientColor_android_centerColor = 7;
			
			// aapt resource value: 3
			public const int GradientColor_android_centerX = 3;
			
			// aapt resource value: 4
			public const int GradientColor_android_centerY = 4;
			
			// aapt resource value: 1
			public const int GradientColor_android_endColor = 1;
			
			// aapt resource value: 10
			public const int GradientColor_android_endX = 10;
			
			// aapt resource value: 11
			public const int GradientColor_android_endY = 11;
			
			// aapt resource value: 5
			public const int GradientColor_android_gradientRadius = 5;
			
			// aapt resource value: 0
			public const int GradientColor_android_startColor = 0;
			
			// aapt resource value: 8
			public const int GradientColor_android_startX = 8;
			
			// aapt resource value: 9
			public const int GradientColor_android_startY = 9;
			
			// aapt resource value: 6
			public const int GradientColor_android_tileMode = 6;
			
			// aapt resource value: 2
			public const int GradientColor_android_type = 2;
			
			// aapt resource value: { 0x10100C4,0x10100EB,0x10100F1,0x7F010001,0x7F010002,0x7F010003,0x7F010004,0x7F010005,0x7F010011,0x7F010013,0x7F010014,0x7F010015 }
			public static int[] RecyclerView = new int[] {
					16842948,
					16842987,
					16842993,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771985,
					2130771987,
					2130771988,
					2130771989};
			
			// aapt resource value: 1
			public const int RecyclerView_android_clipToPadding = 1;
			
			// aapt resource value: 2
			public const int RecyclerView_android_descendantFocusability = 2;
			
			// aapt resource value: 0
			public const int RecyclerView_android_orientation = 0;
			
			// aapt resource value: 3
			public const int RecyclerView_fastScrollEnabled = 3;
			
			// aapt resource value: 4
			public const int RecyclerView_fastScrollHorizontalThumbDrawable = 4;
			
			// aapt resource value: 5
			public const int RecyclerView_fastScrollHorizontalTrackDrawable = 5;
			
			// aapt resource value: 6
			public const int RecyclerView_fastScrollVerticalThumbDrawable = 6;
			
			// aapt resource value: 7
			public const int RecyclerView_fastScrollVerticalTrackDrawable = 7;
			
			// aapt resource value: 8
			public const int RecyclerView_layoutManager = 8;
			
			// aapt resource value: 9
			public const int RecyclerView_reverseLayout = 9;
			
			// aapt resource value: 10
			public const int RecyclerView_spanCount = 10;
			
			// aapt resource value: 11
			public const int RecyclerView_stackFromEnd = 11;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
